<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
 <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>    
<!DOCTYPE html>    
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Edit Test</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css">
    <script src="main.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
	
	<script src="https://cdn.ckeditor.com/4.11.4/standard/ckeditor.js"></script>
</head>
<body>
    <nav class="navbar navbar-light bg-info">
        <h5>
			<div style="float:left;">
				<img src="<c:url value="/images/img1.png"/>" style='padding-right:20px; height:60px; width:80px'/>
			</div>
			<div style="float:right; color:white; padding-top:5px">
				<p>
					<br>National Institute of Technology, Calicut
				</p>
			</div>
			<div style="clear: left;">
			</div>
		</h5>
    </nav>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <ul class="navbar-nav">
            <li class="nav-item">
				<a class="nav-link text-info" href="welcomef">Home</a>
            </li>
            <li class="nav-item  dropdown">
				<a class="nav-link  text-info dropdown-toggle" data-toggle="dropdown" href="#">Add User
				</a>
				<div class="dropdown-menu">
        			<a class="dropdown-item text-info" href="fas">Student</a>
				 </div>
            </li>
			<li class="nav-item  dropdown">
				<a class="nav-link text-info dropdown-toggle" data-toggle="dropdown" href="#">Edit User
				</a>
				<div class="dropdown-menu">
        			<a class="dropdown-item text-info" href="frs">Student</a>
				</div>
            </li>
			<li class="nav-item  dropdown">
				<a class="nav-link text-info dropdown-toggle" data-toggle="dropdown" href="#">Change Password
				</a>
				<div class="dropdown-menu">
        			<a class="dropdown-item text-info" href="ffp">Faculty</a>
				</div>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
			<li class="nav-item">
				<a class="nav-link" href="logout">Logout</a>
            </li>
        </ul>  
    </nav>
	<br>
	<div class="container" align="center">
	
	<c:forEach items="${testlist}" var="testlist">
	<form method="POST" action="ffet1">
		<h1>Edit Test</h1>
			<table class="table table-borderless">
				<tbody>
      				<tr>
        				<td>Test ID:</td>
        				<td>
        				
                    			<option value="${testlist.test_id}">${testlist.test_id}</option>
                    			<input type="hidden" name="test_id" value="${testlist.test_id}">
                    			<input type="hidden" name="no_que" value="${testlist.no_que}">
                    	
      					</td>
					</tr>
      				<tr>
        				<td>Test Name:</td>
        				<td>
                    			<option value="${testlist.test_name}">${testlist.test_name}</option>
                    			<input type="hidden" name="test_name" value="${testlist.test_name}">
                    	</td>
					</tr>
      				<tr>
        				<td>Generated By:</td>
        				<td>
        					<c:forEach items="${f_username}" var="f_username">
                    			<option value="${f_username}">${f_username}</option>
                    			<input type="hidden" name="f_username" value="${f_username}">
                    		</c:forEach>
        				</td>
					</tr>
					
				<tr>
    						<td>Course:</td>
    						<td>
    							<select name="test_course" onchange="SemOptions(this.value)" value="${testlist.test_course}" style="width: 150px;" id="test_course"  required>
 			 						<option value="B.Tech.">B.Tech.</option>
  			 						<option value="M.Tech.">M.Tech.</option>
  			 						<option value="MCA">MCA</option>
			 					</select>
    						</td>
    						<td>Semester:</td>
    						<td>
    							<select name="test_sem" id="test_sem" style="width: 150px;">
    								<option value="${testlist.test_sem}" selected>${testlist.test_sem}</option>
			 					</select>
			 				</td>
    			</tr>
    			<tr>
    				<td>
    					Starts on:
    				</td>
    			</tr>
				<tr>
					<td>
						Date:
					</td>
					<td>
						<input type="date" name="test_startDate" id="test_startDate" value="${testlist.test_startDate}" onchange="setmaxDate(this.value)" required>
					</td>
					<td>
						Timing: 
					</td>
					<td>
						Hour(s):<input type="number" name="test_shr" value="${testlist.test_shr}" min="0" max="23" required>
					</td>
					<td>
						Minute(s):<input type="number" name="test_smin" value="${testlist.test_smin}" min="0" max="59" required>
					</td>
				</tr><tr>
    				<td>
    					Last Day of Submission:
    				</td>
    			</tr>
				<tr>
					<td>
						Date:
					</td>
					<td>
						<input type="date" name="test_endDate" id="test_endDate" value="${testlist.test_endDate}" required>
					</td>
					<td>
						Timing: 
					</td>
					<td>
						Hour(s):<input type="number" name="test_hr" value="${testlist.test_hr}" min="0" max="23" required>
					</td>
					<td>
						Minute(s):<input type="number" name="test_min" value="${testlist.test_min}" min="0" max="59" required>
					</td>
				</tr>
				</tbody>
			</table>
		<button type="submit" value="Submit" class="btn btn-info btn-lg">Submit</button>
	</form>
	</c:forEach>
	<hr>
	<br>
	<h3>Question(s)</h3>
	<br><br>
    			
	<c:forEach items="${quelist}" var="quelist">
		<form method="POST" action="ffet2" >
			<c:forEach items="${testlist}" var="testlist">
				<input type="hidden" name="test_id" value="${testlist.test_id}">
			</c:forEach>
			<table class="table table-borderless">
				<tbody>
					<tr>
						<td>
							Que ${quelist.que_no}
							<input type="hidden" name="que_no" value="${quelist.que_no}">
						</td>
						<td>
							<textarea class="form-control" name="que"  class="ckeditor">${quelist.que}</textarea>
						</td>	
					</tr>
					<tr>
						<td>
							Test cases
						</td>
						<td>
							<textarea class="form-control" name="cases">${quelist.que_cases}</textarea>
						</td>
					</tr>
					<tr>
						<td>
							Number of files to upload:
						</td>
						<td>
							<input type="number"  min="1" name="no_files"  value="${quelist.no_files}" required>
						</td>
						<td>
							<button type="submit" value="Submit" class="btn btn-info btn-lg">Update</button>
						</td>	
					</tr>
				</tbody>
			</table>
		</form>
		<hr>	
	</c:forEach>
	</div>
	<script>

	var today = new Date();
	var dd = today.getDate();
	var mm = today.getMonth()+1; //January is 0!
	var yyyy = today.getFullYear();
	 if(dd<10){
	        dd='0'+dd
	    } 
	    if(mm<10){
	        mm='0'+mm
	    } 

	today = yyyy+'-'+mm+'-'+dd;
	document.getElementById("test_startDate").setAttribute("min", today);
		var date = new Date(document.getElementById("test_startDate").value);
	    date.setMonth(date.getMonth()+1);
	    var d = date.getDate();
		var m = date.getMonth();
		var yy = date.getFullYear();
	    if(m<10)
	    {
	        m='0'+m
	    }
		date= yy+'-'+m+'-'+d; 
		document.getElementById("test_endDate").setAttribute("min", date);
		
		
		date = new Date(document.getElementById("test_startDate").value);
		    date.setMonth(date.getMonth()+3);
		    d = date.getDate();
			m = date.getMonth();
			yy = date.getFullYear();
		    if(m<10)
		    {
		        m='0'+m
		    }
			date= yy+'-'+m+'-'+d;
		    document.getElementById("test_endDate").setAttribute("max", date);
	function SemOptions(x) 
	{
		  if(x=="B.Tech.")
			  {
			  		var ts = document.getElementById("test_sem");
			  	    for(i = ts.options.length - 1 ; i >= 0 ; i--)
			  	    {
			  	        ts.remove(i);
			  	    }
			  	    var option = document.createElement("option");
			    	option.text = "All";
			  		ts.add(option,0);
			  		for(i=1;i<=8;i++)
			  			{
			  				var option = document.createElement("option");
			  		    	option.text = convert(i);
			  		    	var sel = i;  
			  		    	ts.add(option, sel);
			  			}
			  }
		  else if(x=="M.Tech.")
		  {
		  		var ts = document.getElementById("test_sem");
		  	    for(i = ts.options.length - 1 ; i >= 0 ; i--)
		  	    {
		  	        ts.remove(i);
		  	    }
		  	    var option = document.createElement("option");
		    	option.text = "All";
		  		ts.add(option,0);
		  		for(i=1;i<=4;i++)
		  			{
	  					var option = document.createElement("option");
	  		    		option.text = convert(i);
	  		    		var sel = i;  
	  		    		ts.add(option, sel);
		  			}
		  }
		else if(x=="MCA")
		  {
	  		var ts = document.getElementById("test_sem");
	  	    for(i = ts.options.length - 1 ; i >= 0 ; i--)
	  	    {
	  	        ts.remove(i);
	  	    }
	  	    var option = document.createElement("option");
	    	option.text = "All";
	  		ts.add(option,0);
	  		for(i=1;i<=6;i++)
	  			{
  					var option = document.createElement("option");
  		    		option.text = convert(i);
  		    		var sel = i;  
  		    		ts.add(option, sel);
	  			}
	  	}
	}
	function convert(num) 
	{ 
		  if(num < 1){ return "";}
		  if(num >= 40){ return "XL" + convert(num - 40);}
		  if(num >= 10){ return "X" + convert(num - 10);}
		  if(num >= 9){ return "IX" + convert(num - 9);}
		  if(num >= 5){ return "V" + convert(num - 5);}
		  if(num >= 4){ return "IV" + convert(num - 4);}
		  if(num >= 1){ return "I" + convert(num - 1);}  
	}

	function setmaxDate(selected)
	{
		date = new Date(selected);
	    date.setMonth(date.getMonth()+1);
	    d = date.getDate();
		m = date.getMonth();
		yy = date.getFullYear();
	    if(m<10)
	    {
	        m='0'+m
	    }
		date= yy+'-'+m+'-'+d; 
		document.getElementById("test_endDate").setAttribute("min", date);
		
		
		date = new Date(selected);
		    date.setMonth(date.getMonth()+3);
		    d = date.getDate();
			m = date.getMonth();
			yy = date.getFullYear();
		    if(m<10)
		    {
		        m='0'+m
		    }
			date= yy+'-'+m+'-'+d;
		    document.getElementById("test_endDate").setAttribute("max", date);
	}
	CKEDITOR.replace('que', {
	    	      width: '100%',
	    	      height: 100
	    	    });
	    CKEDITOR.editorConfig
	    {
	        config.width = '50%';
	        config.height = '25em';
	    };
	</script>
</body>
</html>